# Generated by Django 5.2.17 on 2026-09-30 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Act',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('short_name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('source_url', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_number', models.CharField(max_length=50)),
                ('title', models.CharField(blank=True, max_length=500)),
                ('text', models.TextField()),
                ('source_url', models.URLField(blank=True)),
                ('act', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='legal.act')),
            ],
            options={
                'ordering': ['act', 'section_number'],
                'constraints': [models.UniqueConstraint(fields=('act', 'section_number'), name='unique_act_section')],
            },
        ),
    ]
